model:
    name: 'CNN'
    learning_rate: 0.0001
    decay_scheduling: ExponentialDecay
    optimizer: 'adam'
    input_shape: (180, 232)

experiment:
    name: 'new'


train_data:
    batch_size: 1
    image_size: (2,2)
    path_file_csv: ''
    y_file: 'file_path: 1'

test_data:
    batch_size: 1
    image_size: (2,2)
    path_file_csv: ''

metrics:

layers:
    features: [32, 64, 128]



callbacks:
    modelcheckpoint:
        filepath: 'direct'
        check_monitor: ''
        checkpoint_mode: ''
        checkpoint_save_best_only: False
        checkpoint_save_weights_only: True
        checkpoint_verbose: ''
    csvlogger:
        filename: ''
        append: True
        separator: ';'
    tensorboard:
        log_dir: ''
        write_graph: True
